apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pacman
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - scmProvider:
          github:
            organization: KabarukhinAlexey-org
            allBranches: true
            tokenRef:
              secretName: pacman-repo-token
              key: token
          filters:
          - repositoryMatch: ^pacman-demo # <- We grab all branches from pacman-demo repository
      - clusters:
          selector:
            matchLabels:
              env: DEV
  template:
    metadata:
      name: pacman-{{branch}}
    spec:
      destination:
        namespace: pacman-{{branch}}
        server: '{{server}}'
      project: default
      source:
        helm:
          parameters:
          - name: imageTag
            value: '{{branch}}-{{sha}}' # <- As the image tag will be used branch name + GIT_COMMIT. Docker images are build in the Jenkins.
        path: pacman
        repoURL: https://github.com/KabarukhinAlexey/pacman-helm.git # <- Since we are installing our application throught to helm then here we are specifying the helm repo but not the app repo.
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
          preserveResourcesOnDeletion: false
        syncOptions:
        - CreateNamespace=true
